[package]
name = "qeda"
description = "The tool for easy creating electronic component libraries"
version = "0.0.3"
authors = ["Shamil <shamil@shamil.ru>", "QEDA Authors"]
repository = "https://github.com/qeda/qeda-rs/"
license = "MIT"
edition = "2018"
readme = "README.md"
exclude = ["scripts/*", ".vscode/*"]

[lib]
name = "qeda"
path = "src/lib.rs"

[dependencies]
clap = "2.33"
crypto-hash = "0.3"
error-chain = "0.12"
hex = "0.3"
linked-hash-map = "0.5"
reqwest = "0.9"
svgdom = "0.17"
termcolor = "1.0"
yaml-rust = "0.4"