[package]
name = "qeda"
description = "The tool for easy creating electronic component libraries"
version = "0.0.1"
authors = ["Noviga <qeda@noviga.com>"]
license = "MIT"
edition = "2018"

[dependencies]
clap = "2.32"
