
name: PR

on:
  pull_request:
    branches: ['**']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup update stable && rustup default stable
          rustup component add rustfmt
          cargo fmt --all -- --check
          rustup component add clippy
          cargo clippy -- -D warnings
          cargo build
          cargo test
